#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=16g,walltime=00:15:00
#PBS -N app-fmri-2-mat
#PBS -V

set -e

echo "running app-fmri-2-mat w/ singularity"
# time singularity exec -e docker://faskowit/app-fmri-2-mat ./run.sh
time singularity exec --writable -e docker://faskowit/app-fmri-2-mat \
	bash -c "./run.sh $@ "
