#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=6g,walltime=00:10:00
#PBS -N app-fmri-2-mat
#PBS -V

set -e

echo "running app-fmri-2-mat w/ singularity"
time singularity exec -e docker://faskowit/app-fmri-2-mat ./run.sh
